from typing import Any, Dict, Optional

import numpy as np
import pandas as pd
from lets_plot import (
    LetsPlot,
    aes,
    as_discrete,
    element_blank,
    facet_grid,
    geom_hline,
    geom_line,
    geom_rect,
    ggplot,
    ggsize,
    labs,
    scale_y_continuous,
    theme_light,
)

from .builder import TimeSeriesBuilder
from .functions import normalize
from .generators import GENERATOR_FUNCS, generate_component

LetsPlot.set_theme(theme_light())


def plot_signal(
    signal=None,
    component_type=None,
    n_timesteps=100,
    rng=None,
    width=500,
    height=250,
    line_color="black",
    line_size=1.5,
    hline_intercept=None,
    normalization: str = "none",
    normalization_kwargs: Optional[Dict[str, Any]] = {},
    title=None,
    **kwargs,
):
    """Plot a time series signal generated by one of the generator functions.

    This function can be used in two ways:
    1. Pass a pre-generated signal array directly
    2. Specify a component_type and parameters to generate a new signal

    Args:
        signal: Pre-generated signal array (optional)
        component_type: Type of component to generate (if signal not provided)
        n_timesteps: Length of time series to generate (if signal not provided)
        rng: Random number generator (if None, creates new one)
        width: Plot width in pixels
        height: Plot height in pixels
        line_color: Color of the signal line
        line_size: Size of the signal line
        hline_intercept: Y-intercept for horizontal line at y=hline_intercept.
            If None, no line is shown.
        normalization: Normalization method. Options: "none", "minmax", "zscore".
            "none" means no normalization, "minmax" scales to [0, 1], "zscore" standardizes.
        normalization_kwargs: Additional parameters for normalization methods.
            For "minmax", you can pass feature_range (tuple of min and max).
        title: Title for the plot. If None, uses name of component type or "Precomputed Signal".
            If you dont want a title, pass an empty string.
        **kwargs: Additional parameters for the generator function

    Returns:
        lets_plot visualization
    """
    # Create default RNG if not provided
    if rng is None:
        rng = np.random.RandomState(None)  # Use system time as seed

    # Generate signal if not provided directly
    if signal is None:
        if component_type is None:
            raise ValueError("Either signal or component_type must be provided")

        if component_type not in GENERATOR_FUNCS:
            raise ValueError(
                f"Unknown component type: {component_type}. "
                f"Valid types are: {', '.join(GENERATOR_FUNCS.keys())}"
            )

        signal = generate_component(component_type, n_timesteps, rng, **kwargs)

    # Ensure signal is numpy array & normalize signal
    signal = np.asarray(signal)
    signal = normalize(signal, method=normalization, **normalization_kwargs)

    # Create dataframe for plotting - using pandas DataFrame to ensure proper types
    n_points = len(signal)
    data = pd.DataFrame({"time": np.arange(n_points), "value": signal})

    # Create the plot
    p = ggplot(data, aes(x="time", y="value")) + geom_line(
        color=line_color, size=line_size
    )

    if hline_intercept is not None:
        p = p + geom_hline(yintercept=hline_intercept, linetype="dashed", color="gray")

    # Get title
    if title is None:
        title = f"{component_type.replace('_', ' ').capitalize() if component_type else 'Precomputed Signal'}"
        title += f" ({normalization} normalized)" if normalization != "none" else ""
    if title and len(title) == 0:
        title = element_blank()

    # Add labels and theme
    p = p + labs(title=title, x="Time Steps", y="Value") + ggsize(width, height)

    return p


def create_visualization_data(
    dataset, sample_indices=None, components_to_include=None, dimensions=None
):
    """Create data for visualization with lets_plot.

    Args:
        dataset: Dataset containing time series data and components.
        sample_indices: Dictionary mapping class labels to sample indices.
            If None, use first sample of each class.
        components_to_include: List of components to include. If None, include all.
            Default components: ["aggregated", "features", "foundation", "noise"]
        dimensions: List of dimensions to include. If None, include all dimensions.

    Returns:
        Prepared DataFrame for visualization.
    """
    # Determine sample indices if not provided
    if sample_indices is None:
        sample_indices = {}
        for class_label in np.unique(dataset["y"]):
            sample_indices[class_label] = np.where(dataset["y"] == class_label)[0][0]

    # Convert sample_indices dict to list of indices
    indices = list(sample_indices.values())

    # Use the to_df method to get the data in the right format
    builder = TimeSeriesBuilder()
    df = builder.to_df(
        dataset,
        samples=indices,
        components=components_to_include,
        dimensions=dimensions,
        format_classes=True,
    )

    return df


def create_feature_rectangles(dataset, sample_indices=None, components_to_include=None):
    """Create rectangle data for feature visualization.

    Args:
        dataset: Dataset containing time series data and components.
        sample_indices: Dictionary mapping class labels to sample indices.
            If None, use first sample of each class.
        components_to_include: List of components to include. If None, include all.

    Returns:
        DataFrame with rectangle coordinates for feature regions.
    """
    # If components_to_include doesn't have aggregated, no need for rectangles
    if components_to_include is not None and "aggregated" not in components_to_include:
        return None

    # Determine sample indices if not provided
    if sample_indices is None:
        sample_indices = {}
        for class_label in np.unique(dataset["y"]):
            sample_indices[class_label] = np.where(dataset["y"] == class_label)[0][0]

    rectangles = []

    # Process each class and sample
    for class_label, idx in sample_indices.items():
        # Extract feature masks for this sample
        if "feature_masks" in dataset:
            for key, mask in dataset["feature_masks"].items():
                # Check if mask is for this class
                if f"class_{class_label}_" in key:
                    sample_mask = mask[idx]

                    # Find contiguous regions in the mask
                    if np.any(sample_mask):
                        changes = np.diff(
                            np.concatenate([[False], sample_mask, [False]]).astype(int)
                        )
                        start_indices = np.where(changes == 1)[0]
                        end_indices = np.where(changes == -1)[0]

                        # Extract feature name from key
                        feature_name = key.replace(f"class_{class_label}_", "")

                        # Create rectangle for each region
                        for start, end in zip(start_indices, end_indices):
                            rectangles.append(
                                {
                                    "class": f"Class {class_label}",
                                    "component": "aggregated",
                                    "feature": feature_name,
                                    "xmin": float(start),
                                    "xmax": float(end),
                                }
                            )

        # If no rectangles found, try to extract from components
        if not any(r["class"] == f"Class {class_label}" for r in rectangles):
            if "components" in dataset:
                comp = dataset["components"][idx]

                # Try feature masks first
                if hasattr(comp, "feature_masks") and comp.feature_masks:
                    for feature_name, feature_mask in comp.feature_masks.items():
                        if np.any(feature_mask):
                            changes = np.diff(
                                np.concatenate([[False], feature_mask, [False]]).astype(
                                    int
                                )
                            )
                            start_indices = np.where(changes == 1)[0]
                            end_indices = np.where(changes == -1)[0]

                            for start, end in zip(start_indices, end_indices):
                                rectangles.append(
                                    {
                                        "class": f"Class {class_label}",
                                        "component": "aggregated",  # Capitalize for visualization display
                                        "feature": feature_name,
                                        "xmin": float(start),
                                        "xmax": float(end),
                                    }
                                )

                # If still no rectangles, try feature values
                if not any(r["class"] == f"Class {class_label}" for r in rectangles):
                    if hasattr(comp, "features") and comp.features:
                        for feature_name, feature_values in comp.features.items():
                            # Find where the feature has non-zero values
                            non_zero = np.abs(feature_values) > 1e-6
                            if np.any(non_zero):
                                changes = np.diff(
                                    np.concatenate([[False], non_zero, [False]]).astype(
                                        int
                                    )
                                )
                                start_indices = np.where(changes == 1)[0]
                                end_indices = np.where(changes == -1)[0]

                                for start, end in zip(start_indices, end_indices):
                                    rectangles.append(
                                        {
                                            "class": f"Class {class_label}",
                                            "component": "Aggregated",  # Capitalize for visualization display
                                            "feature": feature_name,
                                            "xmin": float(start),
                                            "xmax": float(end),
                                        }
                                    )

    if not rectangles:
        return None

    rect_df = pd.DataFrame(rectangles)

    # Ensure correct class ordering
    class_labels = sorted(rect_df["class"].unique(), key=lambda x: int(x.split()[-1]))
    rect_df["class"] = pd.Categorical(
        rect_df["class"], categories=class_labels, ordered=True
    )

    return rect_df


def create_ts_visualization(
    dataset,
    sample_indices=None,
    components=None,
    dimensions=None,
    show_indicators=True,
    line_color="black",
    line_size=1.5,
    hline_intercept=0,
    rect_fill="red",
    rect_alpha=0.25,
    facet_order={"y": "class", "x": "component"},
    free_y=False,
    x_order=1,
    y_order=1,
    panel_width=250,
    panel_height=150,
):
    """Create time series visualization with feature indicators as rectangles.

    Args:
        dataset: Dataset containing time series data and components.
        sample_indices: Dictionary mapping class labels to sample indices.
            If None, use first sample of each class.
        components: List of components to include. Can be used to exclude certain components.
            Default: ["aggregated", "features", "foundation", "noise"]
        dimensions: List of dimensions to include. If None, include all dimensions.
            For multivariate time series, this allows selecting specific dimensions.
        show_indicators: Whether to show feature indicators.
        line_color: Color of the time series lines ("black" or "auto" for colored by class).
        line_size: Size of the time series lines.
        hline_intercept: Y-intercept for horizontal line at y=hline_intercept.
            If None, no line is shown.
        rect_fill: Fill color for feature rectangles.
        rect_alpha: Alpha transparency for feature rectangles.
        facet_order: Order of facets, dict with "x" and "y" keys.
            x corresponds to columns, y to rows.
        free_y: Whether to use free y scales in facets (default=False).
        x_order: Order of x-axis facets. 1=ascending, -1=descending, 0=no order.
            Uses names of the column facet variable.
        y_order: Order of y-axis facets. 1=ascending, -1=descending, 0=no order.
            Uses names of the row facet variable.
        panel_width: Width of each panel in pixels.
        panel_height: Height of each panel in pixels.

    Returns:
        lets_plot visualization or list of visualizations for multivariate data.
    """
    # Default component order - use internal names
    default_components = ["aggregated", "features", "foundation", "noise"]
    components_to_use = components if components is not None else default_components

    # Prepare data for visualization
    df = create_visualization_data(
        dataset, sample_indices, components_to_use, dimensions
    )

    # If no data, return empty plot
    assert len(df) > 0, "No data to display"

    # Determine if we're dealing with a multivariate time series
    is_multivariate = len(df["dim"].unique()) > 1

    # Capitalize component names for display
    current_categories = df["component"].cat.categories
    component_display_names = [c.capitalize() for c in current_categories]
    df = df.copy()
    df["component"] = pd.Categorical(
        [c.capitalize() for c in df["component"].astype(str)],
        categories=component_display_names,
        ordered=True,
    )

    # Create feature rectangles if needed
    rectangles = None
    if show_indicators:
        rectangles = create_feature_rectangles(
            dataset, sample_indices, components_to_use
        )
        # Also capitalize component names in rectangles if they exist
        if rectangles is not None:
            rectangles = rectangles.copy()
            if "component" in rectangles.columns:
                # Make sure component names are capitalized
                rectangles["component"] = rectangles["component"].str.capitalize()

    # For multivariate time series, use a different approach
    if is_multivariate:
        # Get dimensions from the DataFrame
        available_dims = sorted(df["dim"].unique())

        # Simplify visualizations by creating per-dimension plots
        result = plot_multivariate_ts_by_dimension(
            df,
            rectangles,
            line_color=line_color,
            line_size=line_size,
            hline_intercept=hline_intercept,
            rect_fill=rect_fill,
            rect_alpha=rect_alpha,
            free_y=free_y,
            panel_width=panel_width,
            panel_height=panel_height,
        )

        return result

    # For univariate case, use original approach
    # Calculate global y-limits
    y_min = df["value"].min()
    y_max = df["value"].max()
    padding = (y_max - y_min) * 0.15
    y_min = float(y_min - padding)
    y_max = float(y_max + padding)

    # Calculate plot dimensions
    n_components = len(df["component"].unique())
    n_classes = len(df["class"].unique())
    total_width = panel_width * (
        n_components
        if "x" in facet_order and facet_order["x"] == "component"
        else n_classes
    )
    total_height = panel_height * (
        n_classes
        if "y" in facet_order and facet_order["y"] == "class"
        else n_components
    )

    # Start building the plot
    if line_color == "auto":
        # Use colors by class
        p = ggplot(df, aes(x="time", y="value", color=as_discrete("class")))
    else:
        # Use specified line color
        p = ggplot(df, aes(x="time", y="value"))

    if hline_intercept is not None:
        p = p + geom_hline(yintercept=0, linetype="dashed", color="gray")

    # Add rectangles for feature regions
    if show_indicators and rectangles is not None:
        # Set rectangle height to full panel height
        rectangles = rectangles.copy()
        rectangles["ymin"] = y_min
        rectangles["ymax"] = y_max

        # Add rectangles to the plot
        if line_color == "auto":
            # Color rectangles by feature
            p = p + geom_rect(
                data=rectangles,
                mapping=aes(
                    xmin="xmin", xmax="xmax", ymin="ymin", ymax="ymax", fill="feature"
                ),
                alpha=rect_alpha,
                size=0.2,
                color="grey",
            )
        else:
            # Use specified rectangle color
            p = p + geom_rect(
                data=rectangles,
                mapping=aes(xmin="xmin", xmax="xmax", ymin="ymin", ymax="ymax"),
                fill=rect_fill,
                alpha=rect_alpha,
                size=0.2,
                color="grey",
            )

    # Complete the plot
    if line_color == "auto":
        p = p + geom_line(size=line_size)
    else:
        p = p + geom_line(size=line_size, color=line_color)

    # Use regular facet grid with proper ordering
    scales = "free_y" if free_y else "fixed"
    p = p + facet_grid(**facet_order, scales=scales, x_order=x_order, y_order=y_order)

    if not free_y:
        p = p + scale_y_continuous(limits=[y_min, y_max])

    p = p + labs(x="Time Steps", y="Value")
    p = p + ggsize(total_width, total_height)

    return p


def plot_multivariate_ts_by_dimension(
    df,
    rectangles=None,
    line_color="black",
    line_size=1.5,
    hline_intercept=0,
    rect_fill="red",
    rect_alpha=0.25,
    free_y=False,
    panel_width=250,
    panel_height=150,
):
    """Plot multivariate time series with dimensions as separate facet grids.

    This function visualizes multivariate time series by creating facet grids
    that clearly separate dimensions.

    Args:
        df: DataFrame with time series data, already processed by create_visualization_data.
        rectangles: DataFrame with rectangle data for feature indicators.
        line_color: Color of the time series lines.
        line_size: Size of the time series lines.
        hline_intercept: Y-intercept for horizontal line.
        rect_fill: Fill color for feature rectangles.
        rect_alpha: Alpha transparency for feature rectangles.
        free_y: Whether to use free y scales in facets.
        panel_width: Width of each panel in pixels.
        panel_height: Height of each panel in pixels.

    Returns:
        lets_plot visualization organized by dimensions.
    """
    # Make a clean copy to avoid modifying the original
    df = df.copy()

    # Get unique dimensions and create a label for plotting
    dimensions = sorted(df["dim"].unique())

    # Create separate plots for each dimension
    plots = []

    for dim in dimensions:
        # Filter data for this dimension
        dim_df = df[df["dim"] == dim].copy()

        # Calculate y-limits for this dimension
        y_min = dim_df["value"].min()
        y_max = dim_df["value"].max()
        padding = (y_max - y_min) * 0.15 if y_max > y_min else 0.1
        y_min = float(y_min - padding)
        y_max = float(y_max + padding)

        # Prepare rectangles for this dimension if they exist
        dim_rects = None
        if rectangles is not None and len(rectangles) > 0:
            dim_rects = rectangles.copy()
            dim_rects["ymin"] = y_min
            dim_rects["ymax"] = y_max

        # Start building the plot
        if line_color == "auto":
            p = ggplot(dim_df, aes(x="time", y="value", color=as_discrete("class")))
        else:
            p = ggplot(dim_df, aes(x="time", y="value"))

        # Add horizontal reference line if specified
        if hline_intercept is not None:
            p = p + geom_hline(yintercept=0, linetype="dashed", color="gray")

        # Add rectangles for feature indicators if available
        if dim_rects is not None:
            if line_color == "auto":
                p = p + geom_rect(
                    data=dim_rects,
                    mapping=aes(
                        xmin="xmin",
                        xmax="xmax",
                        ymin="ymin",
                        ymax="ymax",
                        fill="feature",
                    ),
                    alpha=rect_alpha,
                    size=0.2,
                    color="grey",
                )
            else:
                p = p + geom_rect(
                    data=dim_rects,
                    mapping=aes(xmin="xmin", xmax="xmax", ymin="ymin", ymax="ymax"),
                    fill=rect_fill,
                    alpha=rect_alpha,
                    size=0.2,
                    color="grey",
                )

        # Add the time series lines
        if line_color == "auto":
            p = p + geom_line(size=line_size)
        else:
            p = p + geom_line(size=line_size, color=line_color)

        # Use a simple facet grid with class and component
        p = p + facet_grid(
            y="class", x="component", scales="free_y" if free_y else "fixed"
        )

        if not free_y:
            p = p + scale_y_continuous(limits=[y_min, y_max])

        # Add title and labels
        p = p + labs(title=f"Dimension {dim}", x="Time Steps", y="Value")

        # Calculate plot dimensions
        n_components = len(dim_df["component"].unique())
        n_classes = len(dim_df["class"].unique())
        p = p + ggsize(panel_width * n_components, panel_height * n_classes)

        plots.append(p)

    # Return the first plot if only one dimension
    if len(plots) == 1:
        return plots[0]

    # For multiple dimensions, return all plots
    return plots


def plot_multivariate_ts(
    dataset,
    sample_indices=None,
    components=None,
    dimensions=None,
    show_indicators=True,
    line_color="black",
    line_size=1.5,
    hline_intercept=0,
    rect_fill="red",
    rect_alpha=0.25,
    free_y=False,
    panel_width=250,
    panel_height=150,
):
    """Plot multivariate time series with separate facet grids for each class.

    This function is useful when the number of dimensions is too large for a single
    facet grid. It creates a separate grid for each class.

    Args:
        dataset: Dataset containing time series data and components.
        sample_indices: Dictionary mapping class labels to sample indices.
            If None, use first sample of each class.
        components: List of components to include.
            Default: ["aggregated", "features", "foundation", "noise"]
        dimensions: List of dimensions to include. If None, include all dimensions.
        show_indicators: Whether to show feature indicators.
        line_color: Color of the time series lines.
        line_size: Size of the time series lines.
        hline_intercept: Y-intercept for horizontal line.
        rect_fill: Fill color for feature rectangles.
        rect_alpha: Alpha transparency for feature rectangles.
        free_y: Whether to use free y scales in facets.
        panel_width: Width of each panel in pixels.
        panel_height: Height of each panel in pixels.

    Returns:
        List of lets_plot visualizations, one per class.
    """
    # Default components
    default_components = ["aggregated", "features", "foundation", "noise"]
    components_to_use = components if components is not None else default_components

    # Determine sample indices if not provided
    if sample_indices is None:
        sample_indices = {}
        for class_label in np.unique(dataset["y"]):
            sample_indices[class_label] = np.where(dataset["y"] == class_label)[0][0]

    # Get all data first
    df = create_visualization_data(
        dataset, sample_indices, components_to_use, dimensions
    )

    # Create feature rectangles if needed
    rectangles = None
    if show_indicators:
        rectangles = create_feature_rectangles(
            dataset, sample_indices, components_to_use
        )

    # Split by class
    plots = []
    for class_name in df["class"].unique():
        # Filter data for this class
        class_df = df[df["class"] == class_name].copy()

        # Add dimension display
        class_df["dim_display"] = "Dim " + class_df["dim"].astype(str)
        class_df["dim_display"] = pd.Categorical(
            class_df["dim_display"],
            categories=["Dim " + str(d) for d in sorted(class_df["dim"].unique())],
            ordered=True,
        )

        # Calculate y limits for this class
        y_min = class_df["value"].min()
        y_max = class_df["value"].max()
        padding = (y_max - y_min) * 0.15
        y_min = float(y_min - padding)
        y_max = float(y_max + padding)

        # Capitalize component names for display
        current_categories = (
            class_df["component"].cat.categories
            if hasattr(class_df["component"], "cat")
            else class_df["component"].unique()
        )
        component_display_names = [c.capitalize() for c in current_categories]
        class_df["component"] = pd.Categorical(
            [c.capitalize() for c in class_df["component"].astype(str)],
            categories=component_display_names,
            ordered=True,
        )

        # Calculate plot dimensions
        n_components = len(class_df["component"].unique())
        n_dimensions = len(class_df["dim"].unique())
        total_width = panel_width * n_components
        total_height = panel_height * n_dimensions

        # Filter rectangles for this class if they exist
        class_rectangles = None
        if rectangles is not None:
            class_rectangles = rectangles[rectangles["class"] == class_name].copy()
            if len(class_rectangles) > 0:
                class_rectangles["ymin"] = y_min
                class_rectangles["ymax"] = y_max

                # Add dimension display if it's missing and there are _dim markers in feature names
                if "dim_display" not in class_rectangles.columns:

                    def extract_dim(feature_name):
                        if "_dim" in str(feature_name):
                            parts = str(feature_name).split("_dim")
                            return "Dim " + parts[-1]
                        return "Dim 0"  # Default dimension

                    class_rectangles["dim_display"] = class_rectangles["feature"].apply(
                        extract_dim
                    )

        # Build plot for this class
        if line_color == "auto":
            p = ggplot(
                class_df, aes(x="time", y="value", color=as_discrete("component"))
            )
        else:
            p = ggplot(class_df, aes(x="time", y="value"))

        if hline_intercept is not None:
            p = p + geom_hline(yintercept=0, linetype="dashed", color="gray")

        # Add rectangles if available
        if (
            show_indicators
            and class_rectangles is not None
            and len(class_rectangles) > 0
        ):
            if line_color == "auto":
                p = p + geom_rect(
                    data=class_rectangles,
                    mapping=aes(
                        xmin="xmin",
                        xmax="xmax",
                        ymin="ymin",
                        ymax="ymax",
                        fill="feature",
                    ),
                    alpha=rect_alpha,
                    size=0.2,
                    color="grey",
                )
            else:
                p = p + geom_rect(
                    data=class_rectangles,
                    mapping=aes(xmin="xmin", xmax="xmax", ymin="ymin", ymax="ymax"),
                    fill=rect_fill,
                    alpha=rect_alpha,
                    size=0.2,
                    color="grey",
                )

        # Add lines
        if line_color == "auto":
            p = p + geom_line(size=line_size)
        else:
            p = p + geom_line(size=line_size, color=line_color)

        # Create facet grid with dimensions as rows and components as columns
        p = p + facet_grid(
            y="dim_display", x="component", scales="free_y" if free_y else "fixed"
        )

        if not free_y:
            p = p + scale_y_continuous(limits=[y_min, y_max])

        p = p + labs(title=class_name, x="Time Steps", y="Value")
        p = p + ggsize(total_width, total_height)

        plots.append(p)

    # Return the list of plots, one per class
    return plots


def plot_sample(
    X,
    y=None,
    feature_masks=None,
    components=None,
    sample_idx=0,
    components_to_include=None,
    line_color="black",
    rect_fill="red",
    free_y=False,
    panel_width=225,
    panel_height=175,
):
    """Plot a time series sample with its components and feature masks using lets_plot.

    Args:
        X: Time series data.
        y: Class labels.
        feature_masks: Dictionary of feature masks.
        components: List of TimeSeriesComponents objects.
        sample_idx: Index of the sample to plot.
        components_to_include: List of components to include.
        line_color: Color of the time series lines ("black" or "auto" for colored by class).
        rect_fill: Fill color for feature rectangles.
        free_y: Whether to use free y scales in facets.
        panel_width: Width of each panel in pixels.
        panel_height: Height of each panel in pixels.

    Returns:
        lets_plot visualization.
    """
    # Prepare dataset in the expected format
    dataset = {"X": X, "components": components}

    if y is not None:
        dataset["y"] = y
    else:
        # Create dummy labels if not provided
        dataset["y"] = np.zeros(len(X))

    if feature_masks is not None:
        dataset["feature_masks"] = feature_masks

    # Set up sample indices
    class_label = dataset["y"][sample_idx]
    sample_indices = {class_label: sample_idx}

    # Create and return plot
    return create_ts_visualization(
        dataset,
        sample_indices=sample_indices,
        components=components_to_include,
        line_color=line_color,
        rect_fill=rect_fill,
        free_y=free_y,
        panel_width=panel_width,
        panel_height=panel_height,
    )


def plot_class_comparison(
    dataset,
    components_to_include=None,
    line_color="auto",
    rect_fill="red",
    free_y=False,
    panel_width=225,
    panel_height=175,
):
    """Plot comparison of classes with feature indicators using lets_plot.

    Args:
        dataset: Dataset containing time series data and components.
        components_to_include: List of components to include.
        line_color: Color of the time series lines ("black" or "auto" for colored by class).
        rect_fill: Fill color for feature rectangles.
        free_y: Whether to use free y scales in facets.
        panel_width: Width of each panel in pixels.
        panel_height: Height of each panel in pixels.

    Returns:
        lets_plot visualization of class comparison.
    """
    # Get first sample from each class
    sample_indices = {}
    for class_label in np.unique(dataset["y"]):
        sample_indices[class_label] = np.where(dataset["y"] == class_label)[0][0]

    # Default to only showing "Aggregated" for class comparison
    if components_to_include is None:
        components_to_include = ["aggregated"]  # Changed from "Complete Series"

    # Create and return visualization
    return create_ts_visualization(
        dataset,
        sample_indices=sample_indices,
        components=components_to_include,
        show_indicators=True,
        line_color=line_color,
        rect_fill=rect_fill,
        free_y=free_y,
        panel_width=panel_width,
        panel_height=panel_height,
    )
