from typing import Any, Dict, List, Union

import numpy as np
import pandas as pd
from lets_plot import (
    LetsPlot,
    aes,
    as_discrete,
    element_blank,
    facet_grid,
    geom_hline,
    geom_line,
    geom_rect,
    ggplot,
    ggsize,
    labs,
    scale_y_continuous,
    theme_light,
)

from .builder import TimeSeriesBuilder
from .functions import normalize
from .generators import GENERATOR_FUNCS, generate_component

LetsPlot.set_theme(theme_light())


def _ensure_visualization_format(dataset: Dict) -> Dict:
    """Ensure the dataset is in the appropriate format for visualization.

    The visualization code expects data in 'channels_last' format.
    This function checks the format and converts if necessary.

    Args:
        dataset (Dict): Dataset containing time series data and components.

    Returns:
        Dict: Dataset with data in the correct format for visualization.
    """
    # Create a shallow copy to avoid modifying the original
    dataset = dataset.copy()

    # Check if the dataset has metadata specifying the format
    if "metadata" in dataset and "data_format" in dataset["metadata"]:
        data_format = dataset["metadata"]["data_format"]

        # If data is in channels_first format, convert to channels_last for visualization
        if data_format == "channels_first" and "X" in dataset:
            # Use the convert_data_format utility from TimeSeriesBuilder
            dataset = TimeSeriesBuilder.convert_data_format(dataset, "channels_last")

    return dataset


def plot_component(
    signal: np.ndarray = None,
    component_type: str = None,
    n_timesteps: int = 100,
    rng: np.random.RandomState = None,
    width: int = 500,
    height: int = 250,
    line_color: str = "black",
    line_size: float = 1.5,
    hline_intercept: float = None,
    normalization: str = "none",
    normalization_kwargs: Dict[str, Any] = None,
    title: str = None,
    **kwargs: Any,
) -> Any:
    """Plot a time series signal generated by one of the generator functions.

    This function can be used in two ways:
    1. Pass a pre-generated signal array directly
    2. Specify a component_type and parameters to generate a new signal

    Args:
        signal (Optional[np.ndarray]): Pre-generated signal array.
        component_type (Optional[str]): Type of component to generate (if signal not provided).
        n_timesteps (int): Length of time series to generate (if signal not provided).
        rng (Optional[np.random.RandomState]): Random number generator.
        width (int): Plot width in pixels.
        height (int): Plot height in pixels.
        line_color (str): Color of the signal line.
        line_size (float): Size of the signal line.
        hline_intercept (Optional[float]): Y-intercept for horizontal line.
            If None, no line is shown.
        normalization (str): Normalization method. Options: "none", "minmax", "zscore".
            "none" means no normalization, "minmax" scales to [0, 1], "zscore" standardizes.
        normalization_kwargs (Optional[Dict[str, Any]]): Additional parameters for normalization methods.
            For "minmax", you can pass feature_range (tuple of min and max).
        title (Optional[str]): Title for the plot.
        **kwargs (Any): Additional parameters for the generator function.

    Returns:
        Any: lets_plot visualization object.
    """
    # Handle default for normalization_kwargs
    if normalization_kwargs is None:
        normalization_kwargs = {}

    # Create default RNG if not provided
    if rng is None:
        rng = np.random.RandomState(None)  # Use system time as seed

    # Generate signal if not provided directly
    if signal is None:
        if component_type is None:
            raise ValueError("Either signal or component_type must be provided")

        if component_type not in GENERATOR_FUNCS:
            raise ValueError(
                f"Unknown component type: {component_type}. "
                f"Valid types are: {', '.join(GENERATOR_FUNCS.keys())}"
            )

        signal = generate_component(component_type, n_timesteps, rng, **kwargs)

    # Ensure signal is numpy array & normalize signal
    signal = np.asarray(signal)
    signal = normalize(signal, method=normalization, **normalization_kwargs)

    # Create dataframe for plotting - using pandas DataFrame to ensure proper types
    n_points = len(signal)
    data = pd.DataFrame({"time": np.arange(n_points), "value": signal})

    # Create the plot
    p = ggplot(data, aes(x="time", y="value")) + geom_line(
        color=line_color, size=line_size
    )

    if hline_intercept is not None:
        p = p + geom_hline(yintercept=hline_intercept, linetype="dashed", color="gray")

    # Get title
    if title is None:
        title = f"{component_type.replace('_', ' ').capitalize() if component_type else 'Precomputed Signal'}"
        title += f" ({normalization} normalized)" if normalization != "none" else ""
    if title and len(title) == 0:
        title = element_blank()

    # Add labels and theme
    p = p + labs(title=title, x="Time Steps", y="Value") + ggsize(width, height)

    return p


def prepare_plot_data(
    dataset: Dict,
    sample_indices: Union[Dict[int, int], List[int], int, None] = None,
    components_to_include: List[str] = None,
    dimensions: List[int] = None,
) -> pd.DataFrame:
    """Create data for visualization with lets_plot.

    Args:
        dataset (Dict): Dataset containing time series data and components.
        sample_indices (Union[Dict[int, int], List[int], int, None]): Samples to include.
            Can be provided in several formats:
            - Dict[int, int]: Mapping from class labels to sample indices (e.g., {0: 5, 1: 10})
            - List[int]: List of sample indices to include (e.g., [0, 5, 10])
            - int: Single sample index (e.g., 5)
            - None: Use first sample of each class (default)
        components_to_include (Optional[List[str]]): List of components to include. If None, include all.
            Default components: ["aggregated", "features", "foundation"].
        dimensions (Optional[List[int]]): List of dimensions to include. If None, include all dimensions.

    Returns:
        pd.DataFrame: Prepared DataFrame for visualization.
    """
    # Ensure dataset is in channels_last format for visualization
    dataset = _ensure_visualization_format(dataset)

    # Process sample_indices to determine which samples to include
    if sample_indices is None:
        # Default: first sample of each class
        indices_dict = {}
        for class_label in np.unique(dataset["y"]):
            indices_dict[class_label] = np.where(dataset["y"] == class_label)[0][0]
        indices = list(indices_dict.values())
    elif isinstance(sample_indices, dict):
        # Dict mapping class -> index
        indices = list(sample_indices.values())
    elif isinstance(sample_indices, int):
        # Single sample index
        indices = [sample_indices]
    elif isinstance(sample_indices, list):
        # List of sample indices
        indices = sample_indices
    else:
        raise TypeError(
            f"sample_indices must be Dict[int, int], List[int], int, or None, "
            f"got {type(sample_indices)}"
        )

    # Use the to_df method to get the data in the right format
    builder = TimeSeriesBuilder()
    df = builder.to_df(
        dataset,
        samples=indices,
        components=components_to_include,
        dimensions=dimensions,
        format_classes=True,
    )

    return df


def prepare_feature_highlights(
    dataset: Dict,
    sample_indices: Dict[int, int] = None,
    components_to_include: List[str] = None,
    dimensions: Union[int, List[int]] = None,
) -> pd.DataFrame:
    """Create rectangle data for feature visualization.

    Args:
        dataset (Dict): Dataset containing time series data and components.
        sample_indices (Optional[Dict[int, int]]): Dictionary mapping class labels to sample indices.
            If None, use first sample of each class.
        components_to_include (Optional[List[str]]): List of components to include. If None, include all.
        dimensions (Optional[Union[int, List[int]]]): List of dimensions to include or an integer for a
            single dimension. If None, include all dimensions.

    Returns:
        Optional[pd.DataFrame]: DataFrame with rectangle coordinates for feature regions,
            or None if no features found.
    """
    # Ensure dataset is in channels_last format for visualization
    dataset = _ensure_visualization_format(dataset)

    # If components_to_include doesn't have aggregated, no need for rectangles
    if components_to_include is not None and "aggregated" not in components_to_include:
        return None

    # Determine sample indices if not provided
    if sample_indices is None:
        sample_indices = {}
        for class_label in np.unique(dataset["y"]):
            sample_indices[class_label] = np.where(dataset["y"] == class_label)[0][0]

    # Convert dimensions to list if it's a single value
    if dimensions is not None and not isinstance(dimensions, list):
        dimensions = [dimensions]

    rectangles = []

    # Process each class and sample
    for class_label, idx in sample_indices.items():
        # Extract feature masks for this sample
        if "feature_masks" in dataset:
            for key, mask in dataset["feature_masks"].items():
                # Check if mask is for this class
                if f"class_{class_label}_" in key:
                    # Extract dimension from feature name if present
                    dim_match = None
                    if "_dim" in key:
                        # Try to extract dimension number
                        try:
                            dim_parts = key.split("_dim")
                            dim_num = int(dim_parts[-1])
                            dim_match = dim_num
                        except (ValueError, IndexError):
                            pass

                    # Skip if dimensions are specified and this feature is for a different dimension
                    if (
                        dimensions is not None
                        and dim_match is not None
                        and dim_match not in dimensions
                    ):
                        continue

                    sample_mask = mask[idx]

                    # Find contiguous regions in the mask
                    if np.any(sample_mask):
                        changes = np.diff(
                            np.concatenate([[False], sample_mask, [False]]).astype(int)
                        )
                        start_indices = np.where(changes == 1)[0]
                        end_indices = np.where(changes == -1)[0]

                        # Extract feature name from key
                        feature_name = key.replace(f"class_{class_label}_", "")

                        # Create rectangle for each region
                        for start, end in zip(start_indices, end_indices):
                            rect = {
                                "class": f"Class {class_label}",
                                "component": "aggregated",
                                "feature": feature_name,
                                "xmin": float(start),
                                "xmax": float(end),
                            }

                            # Add dimension information if available
                            if dim_match is not None:
                                rect["dim"] = dim_match

                            rectangles.append(rect)

        # If no rectangles found, try to extract from components
        if not any(r["class"] == f"Class {class_label}" for r in rectangles):
            if "components" in dataset:
                comp = dataset["components"][idx]

                # Try feature masks first
                if hasattr(comp, "feature_masks") and comp.feature_masks:
                    for feature_name, feature_mask in comp.feature_masks.items():
                        # Extract dimension if present in the feature name
                        dim_match = None
                        if "_dim" in feature_name:
                            try:
                                dim_parts = feature_name.split("_dim")
                                dim_num = int(dim_parts[-1])
                                dim_match = dim_num
                            except (ValueError, IndexError):
                                pass

                        # Skip if dimensions are specified and this feature is for a different dimension
                        if (
                            dimensions is not None
                            and dim_match is not None
                            and dim_match not in dimensions
                        ):
                            continue

                        if np.any(feature_mask):
                            changes = np.diff(
                                np.concatenate([[False], feature_mask, [False]]).astype(
                                    int
                                )
                            )
                            start_indices = np.where(changes == 1)[0]
                            end_indices = np.where(changes == -1)[0]

                            for start, end in zip(start_indices, end_indices):
                                rect = {
                                    "class": f"Class {class_label}",
                                    "component": "aggregated",
                                    "feature": feature_name,
                                    "xmin": float(start),
                                    "xmax": float(end),
                                }

                                # Add dimension information if available
                                if dim_match is not None:
                                    rect["dim"] = dim_match

                                rectangles.append(rect)

                # If still no rectangles, try feature values
                if not any(r["class"] == f"Class {class_label}" for r in rectangles):
                    if hasattr(comp, "features") and comp.features:
                        for feature_name, feature_values in comp.features.items():
                            # Extract dimension if present in the feature name
                            dim_match = None
                            if "_dim" in feature_name:
                                try:
                                    dim_parts = feature_name.split("_dim")
                                    dim_num = int(dim_parts[-1])
                                    dim_match = dim_num
                                except (ValueError, IndexError):
                                    pass

                            # Skip if dimensions are specified and this feature is for a different dimension
                            if (
                                dimensions is not None
                                and dim_match is not None
                                and dim_match not in dimensions
                            ):
                                continue

                            # Find where the feature has non-zero values
                            non_zero = np.abs(feature_values) > 1e-6
                            if np.any(non_zero):
                                changes = np.diff(
                                    np.concatenate([[False], non_zero, [False]]).astype(
                                        int
                                    )
                                )
                                start_indices = np.where(changes == 1)[0]
                                end_indices = np.where(changes == -1)[0]

                                for start, end in zip(start_indices, end_indices):
                                    rect = {
                                        "class": f"Class {class_label}",
                                        "component": "Aggregated",
                                        "feature": feature_name,
                                        "xmin": float(start),
                                        "xmax": float(end),
                                    }

                                    # Add dimension information if available
                                    if dim_match is not None:
                                        rect["dim"] = dim_match

                                    rectangles.append(rect)

    if not rectangles:
        return None

    rect_df = pd.DataFrame(rectangles)

    # Ensure correct class ordering
    class_labels = sorted(rect_df["class"].unique(), key=lambda x: int(x.split()[-1]))
    rect_df["class"] = pd.Categorical(
        rect_df["class"], categories=class_labels, ordered=True
    )

    return rect_df


def plot_components(
    dataset: Dict,
    samples: Union[int, List[int], Dict[int, int], None] = None,
    components: List[str] = None,
    dimensions: List[int] = None,
    show_indicators: bool = True,
    line_color: str = "black",
    line_size: float = 1.5,
    hline_intercept: float = 0,
    rect_fill: str = "red",
    rect_alpha: float = 0.25,
    facet_order: Dict[str, str] = {"y": "class", "x": "component"},
    free_y: bool = False,
    x_order: int = 1,
    y_order: int = 1,
    panel_width: int = 250,
    panel_height: int = 150,
) -> Union[Any, List[Any]]:
    """Create time series visualization with feature indicators as rectangles.

    This function visualizes time series data by showing its components (aggregated series,
    foundation, features) with options to highlight feature locations.

    Args:
        dataset (Dict): Dataset containing time series data and components.
        samples (Union[int, List[int], Dict[int, int], None]): Specifies which samples to visualize.
            Can be provided in several formats:
            - int: A single sample index (e.g., 5 to show sample at index 5)
            - List[int]: Multiple sample indices (e.g., [0, 10, 20] to show these samples)
            - Dict[int, int]: Mapping from class labels to sample indices
              (e.g., {0: 5, 1: 10} for first sample of class 0, second of class 1)
            - None: Use first sample from each class (default behavior)
        components (Optional[List[str]]): List of components to include. Can be used to exclude
            certain components. Default: ["aggregated", "features", "foundation"].
        dimensions (Optional[List[int]]): List of dimensions to include. If None, include all dimensions.
            For multivariate time series, this allows selecting specific dimensions.
        show_indicators (bool): Whether to show feature indicators.
        line_color (str): Color of the time series lines ("black" or "auto" for colored by class).
        line_size (float): Size of the time series lines.
        hline_intercept (float): Y-intercept for horizontal line at y=hline_intercept.
            If None, no line is shown.
        rect_fill (str): Fill color for feature rectangles.
        rect_alpha (float): Alpha transparency for feature rectangles.
        facet_order (Dict[str, str]): Order of facets, dict with "x" and "y" keys.
            x corresponds to columns, y to rows.
        free_y (bool): Whether to use free y scales in facets.
        x_order (int): Order of x-axis facets. 1=ascending, -1=descending, 0=no order.
            Uses names of the column facet variable.
        y_order (int): Order of y-axis facets. 1=ascending, -1=descending, 0=no order.
            Uses names of the row facet variable.
        panel_width (int): Width of each panel in pixels.
        panel_height (int): Height of each panel in pixels.

    Returns:
        Union[Any, List[Any]]: lets_plot visualization or list of visualizations for multivariate data.

    Raises:
        IndexError: If a sample index is out of range.

    Examples:
        # Show first sample of each class (default)
        plot_components(dataset)

        # Show a specific sample by index
        plot_components(dataset, samples=5)

        # Show multiple specific samples
        plot_components(dataset, samples=[0, 10, 20])

        # Show specific samples from each class
        plot_components(dataset, samples={0: 5, 1: 10})
    """
    # Ensure dataset is in channels_last format for visualization
    dataset = _ensure_visualization_format(dataset)

    # Process samples parameter to get sample_indices dict
    sample_indices = None

    if samples is not None:
        if isinstance(samples, int):
            # Single sample index
            if samples < 0 or samples >= len(dataset["y"]):
                raise IndexError(
                    f"Sample index {samples} is out of range (0-{len(dataset['y']) - 1})"
                )

            # Get class of the sample and create sample_indices dict
            class_label = dataset["y"][samples]
            sample_indices = {class_label: samples}

        elif isinstance(samples, list):
            # Multiple sample indices
            for idx in samples:
                if idx < 0 or idx >= len(dataset["y"]):
                    raise IndexError(
                        f"Sample index {idx} is out of range (0-{len(dataset['y']) - 1})"
                    )

            # Group samples by class
            sample_indices = {}
            for idx in samples:
                class_label = dataset["y"][idx]
                # For multiple samples per class, we'll just use the last one
                # This is because our visualization pipeline expects one sample per class
                sample_indices[class_label] = idx

        elif isinstance(samples, dict):
            # Already in sample_indices format (class -> index mapping)
            sample_indices = samples

            # Validate the indices
            for class_label, idx in sample_indices.items():
                if idx < 0 or idx >= len(dataset["y"]):
                    raise IndexError(
                        f"Sample index {idx} is out of range (0-{len(dataset['y']) - 1})"
                    )

                # Verify the class label matches
                actual_class = dataset["y"][idx]
                if actual_class != class_label:
                    raise ValueError(
                        f"Sample at index {idx} has class {actual_class}, not {class_label} as specified"
                    )

    # Default component order - use internal names
    default_components = ["aggregated", "features", "foundation"]
    components_to_use = components if components is not None else default_components

    # Prepare data for visualization
    df = prepare_plot_data(dataset, sample_indices, components_to_use, dimensions)

    # If no data, return empty plot
    assert len(df) > 0, "No data to display"

    # Determine if we're dealing with a multivariate time series
    is_multivariate = len(df["dim"].unique()) > 1

    # Capitalize component names for display
    current_categories = df["component"].cat.categories
    component_display_names = [c.capitalize() for c in current_categories]
    df = df.copy()
    df["component"] = pd.Categorical(
        [c.capitalize() for c in df["component"].astype(str)],
        categories=component_display_names,
        ordered=True,
    )

    # For multivariate time series, handle rectangles per dimension
    if is_multivariate and show_indicators:
        # For multivariate case, we'll create rectangles that include dimension information
        rectangles = prepare_feature_highlights(
            dataset, sample_indices, components_to_use
        )

        # Also capitalize component names in rectangles if they exist
        if rectangles is not None:
            rectangles = rectangles.copy()
            if "component" in rectangles.columns:
                # Make sure component names are capitalized
                rectangles["component"] = rectangles["component"].str.capitalize()

        # Now call the multivariate plot function with the rectangles
        result = plot_dimensions(
            df,
            rectangles,
            line_color=line_color,
            line_size=line_size,
            hline_intercept=hline_intercept,
            rect_fill=rect_fill,
            rect_alpha=rect_alpha,
            free_y=free_y,
            panel_width=panel_width,
            panel_height=panel_height,
        )

        return result

    # For univariate case or when not showing indicators, use the original approach
    # Create feature rectangles if needed
    rectangles = None
    if show_indicators:
        rectangles = prepare_feature_highlights(
            dataset, sample_indices, components_to_use, dimensions
        )
        # Also capitalize component names in rectangles if they exist
        if rectangles is not None:
            rectangles = rectangles.copy()
            if "component" in rectangles.columns:
                # Make sure component names are capitalized
                rectangles["component"] = rectangles["component"].str.capitalize()

    # For multivariate time series without indicators, still use the specialized function
    if is_multivariate:
        # Simplify visualizations by creating per-dimension plots
        result = plot_dimensions(
            df,
            rectangles,
            line_color=line_color,
            line_size=line_size,
            hline_intercept=hline_intercept,
            rect_fill=rect_fill,
            rect_alpha=rect_alpha,
            free_y=free_y,
            panel_width=panel_width,
            panel_height=panel_height,
        )

        return result

    # For univariate case, use original approach
    # Calculate global y-limits
    y_min = df["value"].min()
    y_max = df["value"].max()
    padding = (y_max - y_min) * 0.001
    y_min = float(y_min - padding)
    y_max = float(y_max + padding)

    # Calculate plot dimensions
    n_components = len(df["component"].unique())
    n_classes = len(df["class"].unique())
    total_width = panel_width * (
        n_components
        if "x" in facet_order and facet_order["x"] == "component"
        else n_classes
    )
    total_height = panel_height * (
        n_classes
        if "y" in facet_order and facet_order["y"] == "class"
        else n_components
    )

    # Start building the plot
    if line_color == "auto":
        # Use colors by class
        p = ggplot(df, aes(x="time", y="value", color=as_discrete("class")))
    else:
        # Use specified line color
        p = ggplot(df, aes(x="time", y="value"))

    if hline_intercept is not None:
        p = p + geom_hline(yintercept=0, linetype="dashed", color="gray")

    # Add rectangles for feature regions
    if show_indicators and rectangles is not None:
        # Set rectangle height to full panel height
        rectangles = rectangles.copy()
        rectangles["ymin"] = y_min
        rectangles["ymax"] = y_max

        # Add rectangles to the plot
        if line_color == "auto":
            # Color rectangles by feature
            p = p + geom_rect(
                data=rectangles,
                mapping=aes(
                    xmin="xmin", xmax="xmax", ymin="ymin", ymax="ymax", fill="feature"
                ),
                alpha=rect_alpha,
                size=0.2,
                color="grey",
            )
        else:
            # Use specified rectangle color
            p = p + geom_rect(
                data=rectangles,
                mapping=aes(xmin="xmin", xmax="xmax", ymin="ymin", ymax="ymax"),
                fill=rect_fill,
                alpha=rect_alpha,
                size=0.2,
                color="grey",
            )

    # Complete the plot
    if line_color == "auto":
        p = p + geom_line(size=line_size)
    else:
        p = p + geom_line(size=line_size, color=line_color)

    # Use regular facet grid with proper ordering
    scales = "free_y" if free_y else "fixed"
    p = p + facet_grid(**facet_order, scales=scales, x_order=x_order, y_order=y_order)

    if not free_y:
        p = p + scale_y_continuous(limits=[y_min, y_max])

    p = p + labs(x="Time Steps", y="Value")
    p = p + ggsize(total_width, total_height)

    return p


def plot_dimensions(
    df: pd.DataFrame,
    rectangles: pd.DataFrame = None,
    line_color: str = "black",
    line_size: float = 1.5,
    hline_intercept: float = 0,
    rect_fill: str = "red",
    rect_alpha: float = 0.25,
    free_y: bool = False,
    panel_width: int = 250,
    panel_height: int = 150,
) -> Union[Any, List[Any]]:
    """Plot multivariate time series with dimensions as separate facet grids.

    This function visualizes multivariate time series by creating facet grids
    that clearly separate dimensions.

    Args:
        df (pd.DataFrame): DataFrame with time series data, already processed by prepare_plot_data.
        rectangles (Optional[pd.DataFrame]): DataFrame with rectangle data for feature indicators.
        line_color (str): Color of the time series lines.
        line_size (float): Size of the time series lines.
        hline_intercept (float): Y-intercept for horizontal line.
        rect_fill (str): Fill color for feature rectangles.
        rect_alpha (float): Alpha transparency for feature rectangles.
        free_y (bool): Whether to use free y scales in facets.
        panel_width (int): Width of each panel in pixels.
        panel_height (int): Height of each panel in pixels.

    Returns:
        Union[Any, List[Any]]: lets_plot visualization organized by dimensions.
    """
    # Make a clean copy to avoid modifying the original
    df = df.copy()

    # Get unique dimensions and create a label for plotting
    dimensions = sorted(df["dim"].unique())

    # Create separate plots for each dimension
    plots = []

    for dim in dimensions:
        # Filter data for this dimension
        dim_df = df[df["dim"] == dim].copy()

        # Calculate y-limits for this dimension
        y_min = dim_df["value"].min()
        y_max = dim_df["value"].max()
        padding = (y_max - y_min) * 0.15 if y_max > y_min else 0.1
        y_min = float(y_min - padding)
        y_max = float(y_max + padding)

        # Filter rectangles for this dimension if they exist
        dim_rects = None
        if rectangles is not None and len(rectangles) > 0:
            # Filter rectangles by dimension if the 'dim' column exists
            if "dim" in rectangles.columns:
                dim_rects = rectangles[rectangles["dim"] == dim].copy()
            else:
                # Try to extract dimension from feature names if dim column doesn't exist
                dim_rects = rectangles.copy()
                dim_rects = dim_rects[
                    dim_rects["feature"].apply(
                        lambda f: f"_dim{dim}" in str(f)
                        or not any(f"_dim{d}" in str(f) for d in dimensions)
                    )
                ]

            if len(dim_rects) > 0:
                dim_rects["ymin"] = y_min
                dim_rects["ymax"] = y_max

        # Start building the plot
        if line_color == "auto":
            p = ggplot(dim_df, aes(x="time", y="value", color=as_discrete("class")))
        else:
            p = ggplot(dim_df, aes(x="time", y="value"))

        # Add horizontal reference line if specified
        if hline_intercept is not None:
            p = p + geom_hline(yintercept=0, linetype="dashed", color="gray")

        # Add rectangles for feature indicators if available
        if dim_rects is not None:
            if line_color == "auto":
                p = p + geom_rect(
                    data=dim_rects,
                    mapping=aes(
                        xmin="xmin",
                        xmax="xmax",
                        ymin="ymin",
                        ymax="ymax",
                        fill="feature",
                    ),
                    alpha=rect_alpha,
                    size=0.2,
                    color="grey",
                )
            else:
                p = p + geom_rect(
                    data=dim_rects,
                    mapping=aes(xmin="xmin", xmax="xmax", ymin="ymin", ymax="ymax"),
                    fill=rect_fill,
                    alpha=rect_alpha,
                    size=0.2,
                    color="grey",
                )

        # Add the time series lines
        if line_color == "auto":
            p = p + geom_line(size=line_size)
        else:
            p = p + geom_line(size=line_size, color=line_color)

        # Use a simple facet grid with class and component
        p = p + facet_grid(
            y="class", x="component", scales="free_y" if free_y else "fixed"
        )

        if not free_y:
            p = p + scale_y_continuous(limits=[y_min, y_max])

        # Add title and labels
        p = p + labs(title=f"Dimension {dim}", x="Time steps", y="Value")

        # Calculate plot dimensions
        n_components = len(dim_df["component"].unique())
        n_classes = len(dim_df["class"].unique())
        p = p + ggsize(panel_width * n_components, panel_height * n_classes)

        plots.append(p)

    # Return the first plot if only one dimension
    if len(plots) == 1:
        return plots[0]

    # For multiple dimensions, return all plots
    return plots


def plot_by_class(
    dataset: Dict,
    sample_indices: Dict[int, int] = None,
    components: List[str] = None,
    dimensions: List[int] = None,
    show_indicators: bool = True,
    line_color: str = "black",
    line_size: float = 1.5,
    hline_intercept: float = 0,
    rect_fill: str = "red",
    rect_alpha: float = 0.25,
    free_y: bool = False,
    panel_width: int = 250,
    panel_height: int = 150,
) -> List[Any]:
    """Plot multivariate time series with separate facet grids for each class.

    This function is useful when the number of dimensions is too large for a single
    facet grid. It creates a separate grid for each class.

    Args:
        dataset (Dict): Dataset containing time series data and components.
        sample_indices (Optional[Dict[int, int]]): Dictionary mapping class labels to sample indices.
            If None, use first sample of each class.
        components (Optional[List[str]]): List of components to include.
            Default: ["aggregated", "features", "foundation"].
        dimensions (Optional[List[int]]): List of dimensions to include. If None, include all dimensions.
        show_indicators (bool): Whether to show feature indicators.
        line_color (str): Color of the time series lines.
        line_size (float): Size of the time series lines.
        hline_intercept (float): Y-intercept for horizontal line.
        rect_fill (str): Fill color for feature rectangles.
        rect_alpha (float): Alpha transparency for feature rectangles.
        free_y (bool): Whether to use free y scales in facets.
        panel_width (int): Width of each panel in pixels.
        panel_height (int): Height of each panel in pixels.

    Returns:
        List[Any]: List of lets_plot visualizations, one per class.
    """
    # Ensure dataset is in channels_last format for visualization
    dataset = _ensure_visualization_format(dataset)

    # Default components
    default_components = ["aggregated", "features", "foundation"]
    components_to_use = components if components is not None else default_components

    # Determine sample indices if not provided
    if sample_indices is None:
        sample_indices = {}
        for class_label in np.unique(dataset["y"]):
            sample_indices[class_label] = np.where(dataset["y"] == class_label)[0][0]

    # Get all data first
    df = prepare_plot_data(dataset, sample_indices, components_to_use, dimensions)

    # Create feature rectangles if needed
    rectangles = None
    if show_indicators:
        rectangles = prepare_feature_highlights(
            dataset, sample_indices, components_to_use
        )

    # Split by class
    plots = []
    for class_name in df["class"].unique():
        # Filter data for this class
        class_df = df[df["class"] == class_name].copy()

        # Add dimension display
        class_df["dim_display"] = "Dim " + class_df["dim"].astype(str)
        class_df["dim_display"] = pd.Categorical(
            class_df["dim_display"],
            categories=["Dim " + str(d) for d in sorted(class_df["dim"].unique())],
            ordered=True,
        )

        # Calculate y limits for this class
        y_min = class_df["value"].min()
        y_max = class_df["value"].max()
        padding = (y_max - y_min) * 0.02
        y_min = float(y_min - padding)
        y_max = float(y_max + padding)

        # Capitalize component names for display
        current_categories = (
            class_df["component"].cat.categories
            if hasattr(class_df["component"], "cat")
            else class_df["component"].unique()
        )
        component_display_names = [c.capitalize() for c in current_categories]
        class_df["component"] = pd.Categorical(
            [c.capitalize() for c in class_df["component"].astype(str)],
            categories=component_display_names,
            ordered=True,
        )

        # Calculate plot dimensions
        n_components = len(class_df["component"].unique())
        n_dimensions = len(class_df["dim"].unique())
        total_width = panel_width * n_components
        total_height = panel_height * n_dimensions

        # Filter rectangles for this class if they exist
        class_rectangles = None
        if rectangles is not None:
            class_rectangles = rectangles[rectangles["class"] == class_name].copy()
            if len(class_rectangles) > 0:
                class_rectangles["ymin"] = y_min
                class_rectangles["ymax"] = y_max

                # Add dimension display if it's missing and there are _dim markers in feature names
                if "dim_display" not in class_rectangles.columns:

                    def extract_dim(feature_name):
                        if "_dim" in str(feature_name):
                            parts = str(feature_name).split("_dim")
                            return "Dim " + parts[-1]
                        return "Dim 0"  # Default dimension

                    class_rectangles["dim_display"] = class_rectangles["feature"].apply(
                        extract_dim
                    )

        # Build plot for this class
        if line_color == "auto":
            p = ggplot(
                class_df, aes(x="time", y="value", color=as_discrete("component"))
            )
        else:
            p = ggplot(class_df, aes(x="time", y="value"))

        if hline_intercept is not None:
            p = p + geom_hline(yintercept=0, linetype="dashed", color="gray")

        # Add rectangles if available
        if (
            show_indicators
            and class_rectangles is not None
            and len(class_rectangles) > 0
        ):
            if line_color == "auto":
                p = p + geom_rect(
                    data=class_rectangles,
                    mapping=aes(
                        xmin="xmin",
                        xmax="xmax",
                        ymin="ymin",
                        ymax="ymax",
                        fill="feature",
                    ),
                    alpha=rect_alpha,
                    size=0.2,
                    color="grey",
                )
            else:
                p = p + geom_rect(
                    data=class_rectangles,
                    mapping=aes(xmin="xmin", xmax="xmax", ymin="ymin", ymax="ymax"),
                    fill=rect_fill,
                    alpha=rect_alpha,
                    size=0.2,
                    color="grey",
                )

        # Add lines
        if line_color == "auto":
            p = p + geom_line(size=line_size)
        else:
            p = p + geom_line(size=line_size, color=line_color)

        # Create facet grid with dimensions as rows and components as columns
        p = p + facet_grid(
            y="dim_display", x="component", scales="free_y" if free_y else "fixed"
        )

        if not free_y:
            p = p + scale_y_continuous(limits=[y_min, y_max])

        p = p + labs(title=class_name, x="Time Steps", y="Value")
        p = p + ggsize(total_width, total_height)

        plots.append(p)

    # Return the list of plots, one per class
    return plots


def plot_sample(
    X: np.ndarray,
    y: np.ndarray = None,
    feature_masks: Dict[str, np.ndarray] = None,
    components: List[Any] = None,
    sample_idx: int = 0,
    components_to_include: List[str] = None,
    line_color: str = "black",
    rect_fill: str = "red",
    free_y: bool = False,
    panel_width: int = 225,
    panel_height: int = 175,
) -> Any:
    """Plot a time series sample with its components and feature masks using lets_plot.

    Args:
        X (np.ndarray): Time series data.
        y (Optional[np.ndarray]): Class labels.
        feature_masks (Optional[Dict[str, np.ndarray]]): Dictionary of feature masks.
        components (Optional[List[Any]]): List of TimeSeriesComponents objects.
        sample_idx (int): Index of the sample to plot.
        components_to_include (Optional[List[str]]): List of components to include.
        line_color (str): Color of the time series lines ("black" or "auto" for colored by class).
        rect_fill (str): Fill color for feature rectangles.
        free_y (bool): Whether to use free y scales in facets.
        panel_width (int): Width of each panel in pixels.
        panel_height (int): Height of each panel in pixels.

    Returns:
        Any: lets_plot visualization.
    """
    # Prepare dataset in the expected format
    dataset = {"X": X, "components": components}

    if y is not None:
        dataset["y"] = y
    else:
        # Create dummy labels if not provided
        dataset["y"] = np.zeros(len(X))

    if feature_masks is not None:
        dataset["feature_masks"] = feature_masks

    # Set metadata for format detection - assume channels_first if shape is correct
    if len(X.shape) == 3 and X.shape[1] < X.shape[2]:  # Likely channels_first
        dataset["metadata"] = {"data_format": "channels_first"}

    # Set up sample indices
    class_label = dataset["y"][sample_idx]
    sample_indices = {class_label: sample_idx}

    # Create and return plot
    return plot_components(
        dataset,
        samples=sample_indices,
        components=components_to_include,
        line_color=line_color,
        rect_fill=rect_fill,
        free_y=free_y,
        panel_width=panel_width,
        panel_height=panel_height,
    )


def plot_class_comparison(
    dataset: Dict,
    components_to_include: List[str] = None,
    line_color: str = "auto",
    rect_fill: str = "red",
    free_y: bool = False,
    panel_width: int = 225,
    panel_height: int = 175,
) -> Any:
    """Plot comparison of classes with feature indicators using lets_plot.

    Args:
        dataset (Dict): Dataset containing time series data and components.
        components_to_include (Optional[List[str]]): List of components to include.
        line_color (str): Color of the time series lines ("black" or "auto" for colored by class).
        rect_fill (str): Fill color for feature rectangles.
        free_y (bool): Whether to use free y scales in facets.
        panel_width (int): Width of each panel in pixels.
        panel_height (int): Height of each panel in pixels.

    Returns:
        Any: lets_plot visualization of class comparison.
    """
    # Ensure dataset is in channels_last format for visualization
    dataset = _ensure_visualization_format(dataset)

    # Get first sample from each class
    sample_indices = {}
    for class_label in np.unique(dataset["y"]):
        sample_indices[class_label] = np.where(dataset["y"] == class_label)[0][0]

    # Default to only showing "Aggregated" for class comparison
    if components_to_include is None:
        components_to_include = ["aggregated"]  # Changed from "Complete Series"

    # Create and return visualization
    return plot_components(
        dataset,
        samples=sample_indices,
        components=components_to_include,
        show_indicators=True,
        line_color=line_color,
        rect_fill=rect_fill,
        free_y=free_y,
        panel_width=panel_width,
        panel_height=panel_height,
    )
